### ISSUE TITLE
Consider moving this repo to `rust-cli/team`

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-cli/team#131]
rust-lang-nursery is slowly on its way out, and it's always a bit of a dance to go between [github.com/rust-cli](https://github.com/rust-cli/) and this repo.

I propose we follow the lead of [rustwasm/team](https://github.com/rustwasm/team/) and [rustasync/team](https://github.com/rustasync/team/) and move this repo to `rust-cli/team` as a central coordination point.

Thanks!

**Comment by XAMPPRocky** [comment]
I'm in favor of moving, for consistency should the GitHub team name be `rustcli`? Not that I agree with that formatting. I just think it is good to have consistent URL schemes when possible, and we already have `rustwasm` and `rustasync`.
