### ISSUE TITLE
Link to Error or Result?

### ISSUE THREAD

**Issue by oylenshpeegul** [rust-cli/team#158]
On [the errors page](https://github.com/rust-lang-nursery/cli-wg/blob/master/src/tutorial/errors.md), the link *named* std::io::Error actually goes to std::io::Result. Was this intentional? Though the latter does do more explaining and contains a link to the former, it's perhaps a bit confusing.

**Comment by killercup** [comment]
IIRC, it was because the mentioned `read_to_string` function's return type is `std::io::Result` which "hides" that it contains `std::io::Error`. I wouldn't mind chaning it.
