### ISSUE TITLE
Clap 3.0-alpha.1

### ISSUE THREAD

**Issue by killercup** [rust-cli/team#41]
(Might no make it in time for Edition 2018 Preview 2)

First public preview release of Clap 3!

Issues tracked at https://github.com/kbknapp/clap-rs/milestone/73

**Comment by kbknapp** [comment]
The milestone has been updated and anything marked "Good First Issue" is a great target for someone to tackle as it's not blocking on anything else, or overly complicated.

The biggest thing that I haven't started on yet, is moving the completion shell script generation to https://github.com/clap-rs/clap_generate

I still need to go through the v3 Tracking issue and make sure it lines up with the milestone issues (there are a few things out of sync off the top of my head).
