### ISSUE TITLE
Separate binaries for subcommands

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-cli/team#44]
While I was writing https://github.com/rust-clique/man/issues/8, I started to wonder: how could we create `git`-style subcommands?

So in Git, each subcommand is also available as a standalone binary. So `git add` also exists as `git-add`. A cool pattern this is commonly used for is to load extra commands at runtime. If we wanted to add the `git foo` command, all we'd need to do is make `git-foo` available in `$PATH`. I believe `cargo` takes a similar approach too.

I feel this problem is reasonably well understood, but I haven't seen much talk about it. Is there any good prior art available? Can this be done using `clap`? And is there perhaps a way we could document on how to best approach this?

Thanks!

**Comment by uazu** [comment]
On my system `git-add` is a symlink to `git`. So this is using a single executable for many commands and using argv[0] in `git` to select the operation to perform. This is like busybox too. So that's an alternative to what you're discussing really, not an example of it.

**Comment by yoshuawuyts** [comment]
@uazu ohhh, that's neat!

**Comment by epage** [comment]
clap supports both external subcommands and multicall binaries

See the [git example](https://docs.rs/clap/latest/clap/_derive/_cookbook/git_derive/index.html)
